project:
  type: website
  output-dir: docs

website:
  title: "Andrew An Chen"
#  favicon: static/prairie_dog.png
  back-to-top-navigation: true
  google-analytics: "G-85L0ZTT99D"
  page-footer:
    center: "Contact me at [chenandr@musc.edu](mailto:chenandr@musc.edu)"

format:
  html:
    theme: lumen
    css: styles.css

editor: visual

search: false
